## Decomposição LU:

- **Fundamentos:**

O método da eliminação de Gauss consiste em duas partes. A primeira é o procedimento de transformar o sistema de equações padrão em um sistema triangular superior equivalente. Na segunda parte, o sistema equivalente é solucionado com o emprego de substituição regressiva.

Durante o processo de eliminação, a matriz dos coeficiente [a] e o vetor [b] são alterados. Se houver a necessidade de resolver sistemas de equação possuindo a mesma matriz [a], mas diferentes vetores [b] o procedimento deve ser repetido para cada [b]. Seria muito melhor se as operação em [a] pudessem ser dissociadas daquelas realizadas em [b].O Procedimento de eliminação em [a] seria realizado apenas uma vez e então utilizado para resolver o sistema para cada vetor[b].

Um método de solução mais eficiente para este caso é o método de **decomposição LU**. As operações com a matriz [a] são feitas sem utilizar ou alterar o vetor [b]. Este só é usado na parte de substituição da solução.

O método de decomposição LU pode ser usado para resolver um único sistema de equações lineares, porém, ele é especialmente vantasoso na solução de sistemas que têm a mesma matriz [a], mas diferentes vetores [b].

- **O método de decomposição LU:**

Nesso método, a matriz [a] é fatorada em um produto de duas matrizes [L][U]:

$$
    [a] = [L][U] \hspace1cm (1)
$$

A matriz [L] (lower) é uma matriz triangular inferior e a matriz [U] (upper) é uma matriz triangular superior. Com essa decomposição, o sistema de equações a ser resolvido tem a forma:

$$
    [L][U][x] = [b] \hspace1cm (2)
$$

Para resolver essa equação, o produto [U][x] é definido como:

$$
    [U][x] = [y] \hspace1cm (3)
$$

Substituindo na eq.(2), temos:

$$
    [L][y] = [b] \hspace1cm (4)
$$

A solução de [x] é obtida em dois passos. Primeiro, a eq.(4) é resolvida para [y]. Em seguida, a solução [y] é substituida na eq.(3) e então é resolvida pra [x].

Como a matriz [L] é uma matriz triangular inferior, a solução [y] é obtido através do método da substituição progressiva. De forma semelhante, [U] é uma matriz triangular superior e portanto deve ser resolvda com o método de substiruição regressiva.

- **Decomposição LU usando a eliminação de Gauss:**

Quando aplicamos o procedimento de eliminação de Gauss em uma matriz [a], os elementos das matrizes [L] e [U] já são calculados automaticamente. A matriz [U] é a matriz [a] obtida ao final do procedimento de eliminação. A matriz [L] não é escrita explicitamente, mas os elementos que a formam são calculados ao longo do caminho. Os elementos da diafonal de [L] são todos iguais a 1. Os elementos abaixo da diagonal são multiplicadores mij que multiplicam a equação pivô quando ela é usada para eliminar os elementos abaixo do coeficiente pivô.

#### Algoritmos:

- Importações

In [1]:
import numpy as np

- Algoritmos auxiliares:

In [2]:
def factorize(A, dim, disp = False):
    
    # Inicializando a Matriz L com a matriz indentidade:
    L = np.identity(dim)
    
    if disp:
        print('Fatorando [A] em [L][U]:\n')
        print('Matriz A inicial:\n {0}\n'.format(A))
        print('Matriz L inicial:\n {0}\n'.format(L))
        print('Operando sobre a matriz A:\n')
    
    for i in range(0, dim):
        for k in range(i+1, dim):
            L[k,i] = A[k][i]/A[i][i]
            A[k] = A[k] - L[k, i]*A[i]
            
            if disp:
                print('m[{0},{1}] = A[{0},{1}] / A[{0},{0}] = {2}'.format(k,i,L[k,i]))
                print('A[{0}] = A[{0}] - {1} * A[{2}] = {3}\n'.format(k,L[k,i],i,A[k]))
    
    if disp:
        print('Matriz U:\n {0}\n'.format(A))
        print('Matriz L:\n {0}\n'.format(L))
    
    return L, A

In [3]:
def subReg (A, b, dim, disp = False):
    
    #Definindo o n-simo valor do vetor X:
    x = np.zeros(dim)
    x[dim - 1] = b[dim - 1]/A[dim - 1][dim - 1]
    
    #Mostrando dados do componente base:
    if disp:
        print('Base da substituição regressiva (x[n]):')
        print('x[{0}] = b[{0}]/A[{0},{0}]'.format(dim-1))
        print('x[{0}] = {1} || b[{0}] = {2} || A[{0},{0}] = {3}\n'.format(dim-1,x[dim-1],b[dim-1],A[dim-1,dim-1]))
    
    for i in range(dim - 2, -1, -1):
        sum = 0
        
        # Realizando a soma interna de fatores dependentes:
        if disp: print('int {0} - Componentes da soma:'.format(i))
        for j in range(i + 1, dim):
            sum += A[i][j]*x[j]
            if disp: print('A[{0},{1}] = {2} || x[{1}] = {3} || Soma parcial = {4}'.format(i,j,A[i,j],x[j],sum))
        
        # Calculando as soluções regressivamente:
        if disp: print('\nx[{0}] = ( b[{0}] - sum ) / A[{0},{0}]'.format(i))
        x[i] = (b[i] - sum)/A[i,i]
        if disp: print('b[{0}] = {1} || sum = {2} || A[{0},{0}] = {3} || x[{0}] = {4}\n\n'.format(i,b[i],sum,A[i,i], x[i]))
    
    # Retorna o array com as soluções do sistema
    return x

In [4]:
def subProg(A, b, dim, disp = False):
    
    #Definindo o primeiro valor do vetor X:
    x = np.zeros(dim)
    x[0] = b[0]/A[0,0]
    
    #Mostrando dados do componente base:
    if disp: 
        print('Base da substituição progressica (x[0]):')
        print('x[{0}] = b[{0}]/A[{0},{0}]'.format(0))
        print('x[{0}] = {1} || b[{0}] = {2} || A[{0},{0}] = {3}\n'.format(0,x[0],b[0],A[0,0]))
    
    for i in range(1,dim):
        sum = 0
        
        # Realizando a soma interna de fatores dependentes:
        if disp: print('int {0} - Componentes da soma:'.format(i))
        for j in range(0, i):
            sum += A[i,j]*x[j]
            if disp: print('A[{0},{1}] = {2} || x[{1}] = {3} || Soma parcial = {4}'.format(i,j,A[i,j],x[j],sum))
        
        # Calculando as soluções regressivamente:
        if disp: print('\nx[{0}] = ( b[{0}] - sum ) / A[{0},{0}]'.format(i))
        x[i] = (b[i] - sum)/A[i,i]
        if disp: print('b[{0}] = {1} || sum = {2} || A[{0},{0}] = {3} || x[{0}] = {4}\n\n'.format(i,b[i],sum,A[i,i], x[i]))
    
    return x

- Decomposição LU para determinação do vetor [x] (**Método de Doolittle**):

In [5]:
def decompLU(L, U, b, dim, disp = False):
    
    # Primeiro passo: Calcular [L][y] = [b]
    y = subProg(L, b, dim, disp)
    
    # Segundo passo: Calcular [U][x] = [y]
    x = subReg(U, y, dim, disp)
    
    #Retornando o valor de [x]:
    return x

- Determinação da matriz inversa a partir da decomposição LU:

In [6]:
def inversaLU(A, dim, disp = False):
    
    # Decompondo [A] em [L][U]:
    L, U = factorize(A, dim, disp)
    
    b = np.zeros(dim)
    inv = np.empty_like(A)
    for i in range(0, dim):
        b_aux = b.copy()
        b_aux[i] = 1
        inv[i] = decompLU(L,U,b_aux,dim, disp)
    return np.transpose(inv)

#### Teste do algoritmo:

- Teste do método de Doolittle:

In [ ]:
# Informações do programa:

A = np.array(
        [
            [2.0, 5.0, 1.0],
            [4.0, -4.0, 2.0],
            [6.0, -9.0, 1.0]
        ]
    )

b = np.array([-14,-2,-18]);

dim = 3

# Usando as funções:
L, U = factorize(A, dim, disp=True)
decompLU(L,U,b,dim)

- Decomposição LU para determinação do determinante de [A]:

In [7]:
# Informações do programa:

A = np.array(
        [
            [1.0, 12.0, 35.0],
            [-3.0, -20.0, 7.0],
            [5.0, -4.0, -21.0]
        ]
    )

dim = 3

L, U = factorize(A, dim)

print(L,'\n')
print(U,'\n')

# detA = 1
# for i in range(0, dim):
#    detA *= U[i,i]
    
# print('\nO Determinante de A é igual a {0}'.format(detA))

[[ 1.  0.  0.]
 [-3.  1.  0.]
 [ 5. -4.  1.]] 

[[  1.  12.  35.]
 [  0.  16. 112.]
 [  0.   0. 252.]] 



- Decomposição LU para a determinação da matriz inversa:

In [ ]:
A = np.array(
        [
            [6.0, -8.0, 1.0],
            [4.0, -4.0, 2.0],
            [6.0, -9.0, 1.0]
        ]
    )
inversaLU(A,dim=3, disp=True)

##### Algoritmos para prova:

In [ ]:
A = np.array(
        [
            [1.0, 2.0, 3.0],
            [4.0, -4.0, 2.0],
            [6.0, -9.0, 1.0]
        ]
    )