## Eliminação de Gauss-Jordan

O método de eliminação de Gauss-Jordan é um procedimento utilizado para resolver sistemas na forma [a][x] = [b].

O sistemas de equações é manipulado até que se obtenha um sistema equivalente na forma diagonal com elementos normalizados. Sendo assim, ao fim desse processo o novo vetor [b'] é a solução.

Partimos de um sistema do tipo:

<img src="img/eliGaussJordan/img-1.png" width=300 height=400>

E obtemos o novo sistema:

<img src="img/eliGaussJordan/img-2.png" width=200 height=300>

#### Procedimento de eliminação de Gauss-Jordan

O procedimento é muito semelhante ao da eliminação de Gauss, contudo existem duas diferenças:

- A equação pivô é normalizada com a divisão de todos os seus termos pelo coeficiente pivô. Isso faz com que o coeficiente pivô seja igual a 1.

- A equação pivô é utilizada na eliminação dos elementos fora da diagonal principal em **TODAS** as demais equações. Isso significa que o processo de eliminação é aplicado às equações que estão acima e abaixo da equação pivô.

#### Eliminação de Gauss-Jordan com pivotação:

Em alguns casos o elemento pivô da linha seja zero e assim é impossível normalizar a linha, por isso que o método de eleminação de Gauss-Jordan também aceita pivotação.

#### Algoritmos

- Importações

In [1]:
import numpy as np

- Funções

In [5]:
def gaussJordan(A, b, dim, rec=True):
    
    # Imprimindo dados de entrada:
    print('Matriz A com dimensão: {0}'.format(dim))
    print(A, '\n')
    print('Vetor b:\n{0}\n'.format(b))
    
    # Unindo as matrizes no formato [A b]
    A = np.insert(A, dim, b, axis=1)
    print('Nova matriz no formato [A b]:')
    print(A, '\n')
    
    # Pivôtação:
    for i in range(0, dim):
        if A[i,i] == 0:
            print('A linha {0} ( {1} ) não pode ser a linha pivô (coeficiente zero)'.format(i, A[i]))
            for j in range(i + 1, dim):
                if A[j][i] != 0:
                    print('Troca: linha {0} ({1}) -> linha {2} ({3})\n'.format(i,A[i],j,A[j]))
                    linhaTemp = A[i].copy()
                    A[i] = A[j]
                    A[j] = linhaTemp
                    print('Nova matriz pós pivôtação:')
                    print(A, '\n\n')
                    break
        
        # Fim da pivotação
        print('Operações em linhas:\n\n')
        A[i] = A[i]/A[i,i]
        print('A[{0}] = A[{0}]/A[{0},{0}] = {1}\n'.format(i, A[i]))
        for k in range(0, dim):
            if k != i and A[k,i] != 0:
                A[k] = A[k] - A[i]*A[k,i]
                print('A[{0}] = A[{0}] - A[{1}]*A[{0},{1}] = {2}'.format(k, i, A[k]))
        print('\nNova Matriz: \n', A, '\n\n')
                
            
    # Recuperando os valores de b e A
    if rec :
        for i in range(0, dim):
            b[i] = A[i][dim]
        
        A = np.delete(A, dim, 1)
    
        return b

#### Teste dos algoritmos

In [9]:
# Insira aqui a sua matriz A dos coeficientes neste mesmo formato:
A = np.array(
        [
            [1.0, 2.0, -2.0],
            [2.0, 3.0, 1.0],
            [3.0, 2.0, -4.0]
        ]
    )

# Insira a matriz b dos resultados das equações:
b = np.array(
    [9.0, 23.0, 11.0]
)

i = np.identity(3, dtype=float)

# Dimensão da matriz A:
dim = 3

# Chamada da função:
gaussJordan(A,i, dim, False)

Matriz A com dimensão: 3
[[ 1.  2. -2.]
 [ 2.  3.  1.]
 [ 3.  2. -4.]] 

Vetor b:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Nova matriz no formato [A b]:
[[ 1.  2. -2.  1.  0.  0.]
 [ 2.  3.  1.  0.  1.  0.]
 [ 3.  2. -4.  0.  0.  1.]] 

Operações em linhas:


A[0] = A[0]/A[0,0] = [ 1.  2. -2.  1.  0.  0.]

A[1] = A[1] - A[0]*A[1,0] = [ 0. -1.  5. -2.  1.  0.]
A[2] = A[2] - A[0]*A[2,0] = [ 0. -4.  2. -3.  0.  1.]

Nova Matriz: 
 [[ 1.  2. -2.  1.  0.  0.]
 [ 0. -1.  5. -2.  1.  0.]
 [ 0. -4.  2. -3.  0.  1.]] 


Operações em linhas:


A[1] = A[1]/A[1,1] = [-0.  1. -5.  2. -1. -0.]

A[0] = A[0] - A[1]*A[0,1] = [ 1.  0.  8. -3.  2.  0.]
A[2] = A[2] - A[1]*A[2,1] = [  0.   0. -18.   5.  -4.   1.]

Nova Matriz: 
 [[  1.   0.   8.  -3.   2.   0.]
 [ -0.   1.  -5.   2.  -1.  -0.]
 [  0.   0. -18.   5.  -4.   1.]] 


Operações em linhas:


A[2] = A[2]/A[2,2] = [-0.         -0.          1.         -0.27777778  0.22222222 -0.05555556]

A[0] = A[0] - A[2]*A[0,2] = [ 1.          0.          0.       