## Eliminação de Gauss e substituição regressiva:

### Métodos diretos:

Um sistema de equações na forma matricial pode ser manipulado até se transformar em um sistema equivalente, assumindo uma das seguintes formas: **triangular superior, triangular inferior ou diagonal**.

No caso triangular superior, por exemplo, o sistema tem todos os coeficientes nulos abaixo da diagonal e é resolvido por **substituição regressiva**.

Começa com a última equação, que é resolvida para Xn, o valor de Xn é substiruido na equação anterior e assim sucessivamente até alcançar a primeira equação.

Para um sistema de n equações na forma triângular superior, temos uma formula geral:

$$
    x_{n} = \frac{b_n}{a_{nn}} \hspace1.1cm
    x_i = \frac{b_i - \sum^{j = n}_{j = i + 1} a_{ij}b_{j}}{a_{ii}} 
$$

A forma triângular superior e a substituição regressiva são usadas na solução do **método de Gauss**.

### Método de eliminação de Gauss:

Esse método é um procedimento usado para resolver sistemas de equações lineares. Um sistema de equação genérico é manipulado até apresentar a forma **triângular superior**, que é então resolvido com o emprego de substituição regressiva.

Um sistema do tipo:

<img src="img/eliGauss/img-1.png" width=300 height=400>

Após a manipulação fica da seguinte forma:

<img src="img/eliGauss/img-2.png" width=300 height=400>

#### Procedimento de eliminação de Gauss:

**Passo 1:** Nesse passo a primeira equação não é alterada e os termos que incluem x1 são eliminados das demais equações.

A primeira equação (**equação pivô**) possui o coeficiente a11 (**coeficiente ou elemento pivô**). Sendo assim, para eliminar o termo a21x1 a equação pivô é multiplicada por:

$$
    m_{21} = \frac{a_{21}}{a_{11}}
$$

E então subtraida da segunda equação.

Esse mesmo procedimento é repetido a fim de zerar todos os termos abaixo do coeficiente pivô da primeira equação.

**Passo 2 a n:** Após esse passo, um procedimento semelhante é realizado para as próximas equações a fim de zerar todos os elementos abaixo do elemento pivô e assim deixar a matriz na forma triângular superior.

A imagem a seguir resume o procedimento:

<img src="img/eliGauss/img-3.png" width=600 height=700>


#### Dificuldades na aplicação da eliminação de Gauss:

- O elemento pivô é zero:

Como a linha pivô é dividida pelo elemento pivô temos um problema quando o elemento pivô é nulo. Esse problema é resolvido mudando a ordem das linhas. Durante esse processo, chamado **pivôtação**, a linha pivô é trocada por outra linha com elemento pivô não nulo.



#### Algoritmos:

- Importações:

In [4]:
import numpy as np

#### Algoritmos secundários:

- Substituição regressiva:

In [83]:
def subReg (A, b, dim):
    
    #Definindo o n-simo valor do vetor X:
    x = np.zeros(dim)
    x[dim - 1] = b[dim - 1]/A[dim - 1][dim - 1]
    
    #Mostrando dados do componente base:
    print('Base da substituição regressiva (x[n]):')
    print('x[{0}] = b[{0}]/A[{0},{0}]'.format(dim-1))
    print('x[{0}] = {1} || b[{0}] = {2} || A[{0},{0}] = {3}\n'.format(dim-1,x[dim-1],b[dim-1],A[dim-1,dim-1]))
    
    for i in range(dim - 2, -1, -1):
        sum = 0
        
        # Realizando a soma interna de fatores dependentes:
        print('int {0} - Componentes da soma:'.format(i))
        for j in range(i + 1, dim):
            sum += A[i][j]*x[j]
            print('A[{0},{1}] = {2} || x[{1}] = {3} || Soma parcial = {4}]'.format(i,j,A[i,j],x[j],sum))
        
        # Calculando as soluções regressivamente:
        print('\nx[{0}] = ( b[{0}] - sum ) / A[{0},{0}]'.format(i))
        x[i] = (b[i] - sum)/A[i,i]
        print('b[{0}] = {1} || sum = {2} || A[{0},{0}] = {3} || x[{0}] = {4}\n\n'.format(i,b[i],sum,A[i,i], x[i]))
    
    # Retorna o array com as soluções do sistema
    return x
    

- Eliminação de Gauss com pivotação:

In [127]:
def eliGauss(A, b, dim):
    
    # Imprimindo dados de entrada:
    print('Matriz A com dimensão: {0}'.format(dim))
    print(A, '\n')
    print('Vetor b:\n{0}\n'.format(b))
    
    # Unindo as matrizes no formato [A b]
    A = np.insert(A, dim, b, axis=1)
    print('Nova matriz no formato [A b]:')
    print(A, '\n')
    
    # Pivôtação:
    for i in range(0, dim):
        if A[i][i] == 0:
            print('A linha {0} ( {1} ) não pode ser a linha pivô (coeficiente zero)'.format(i, A[i]))
            for j in range(i + 1, dim):
                if A[j][i] != 0:
                    print('Troca: linha {0} ({1}) -> linha {2} ({3})\n'.format(i,A[i],j,A[j]))
                    linhaTemp = A[i].copy()
                    A[i] = A[j]
                    A[j] = linhaTemp
                    print('Nova matriz pós pivôtação:')
                    print(A, '\n\n')
                    break
        
        # Fim da pivotação
        for k in range(i + 1, dim):
            print('Triangulação da matriz A - linha {0}:\n'.format(i+1))
            A[k] = A[k] - A[k][i]/A[i][i]*A[i]
            print('A[{0}] = A[{0}] - A[{0},{1}]/A[{1},{1}]*A[{1}]\n'.format(k,i))
            print(A, '\n\n')
            
    # Recuperando os valores de b e A
    for i in range(0, dim):
        b[i] = A[i][dim]
        
    A = np.delete(A, dim, 1)
    
    # print(A)
    # print(b)
    
    # Usando a substituição regressiva para encontrar a matriz x:
    return subReg(A, b, dim)

##### Testes dos algoritmos:

In [128]:
# Insira aqui a sua matriz A dos coeficientes neste mesmo formato:
A = np.array(
        [
            [0.0, 2.0, 3.0],
            [2.0, 4.0, 5.0],
            [1.0, 0.0, 6.0]
        ]
    )

# Insira a matriz b dos resultados das equações:
b = np.array(
    [1.0, 2.0, 3.0]
)

# Dimensão da matriz A:
dim = 3

# Chamada da função:
eliGauss(A,b, dim)

Matriz A com dimensão: 3
[[0. 2. 3.]
 [2. 4. 5.]
 [1. 0. 6.]] 

Vetor b:
[1. 2. 3.]

Nova matriz no formato [A b]:
[[0. 2. 3. 1.]
 [2. 4. 5. 2.]
 [1. 0. 6. 3.]] 

A linha 0 ( [0. 2. 3. 1.] ) não pode ser a linha pivô (coeficiente zero)
Troca: linha 0 ([0. 2. 3. 1.]) -> linha 1 ([2. 4. 5. 2.])

Nova matriz pós pivôtação:
[[2. 4. 5. 2.]
 [0. 2. 3. 1.]
 [1. 0. 6. 3.]] 


Triangulação da matriz A - linha 1:

A[1] = A[1] - A[1,0]/A[0,0]*A[0]

[[2. 4. 5. 2.]
 [0. 2. 3. 1.]
 [1. 0. 6. 3.]] 


Triangulação da matriz A - linha 1:

A[2] = A[2] - A[2,0]/A[0,0]*A[0]

[[ 2.   4.   5.   2. ]
 [ 0.   2.   3.   1. ]
 [ 0.  -2.   3.5  2. ]] 


Triangulação da matriz A - linha 2:

A[2] = A[2] - A[2,1]/A[1,1]*A[1]

[[2.  4.  5.  2. ]
 [0.  2.  3.  1. ]
 [0.  0.  6.5 3. ]] 


Base da substituição regressiva (x[n]):
x[2] = b[2]/A[2,2]
x[2] = 0.46153846153846156 || b[2] = 3.0 || A[2,2] = 6.5

int 1 - Componentes da soma:
A[1,2] = 3.0 || x[2] = 0.46153846153846156 || Soma parcial = 1.3846153846153846]

x[1] 

array([ 0.23076923, -0.19230769,  0.46153846])