## Métodos interativos de Jacobi e Seidel:

Sistemas de equações lineares também podem ser resolvidos por abordagens interativas. Em princípio, o processo é indêntico ao do método do ponto fixo para equações não lineares.

Na solução de sistemas de queações usando processos interativos, as equações são colocadas em uma forma explícita na qual cada incógnita é escrita em termos das demais incógnitas.

<img src='img/Jacobi-seidel/img-1.png' width=800 height=600>

O processo de solução começa com a escolha da primeira solução estimada. Na primeira interação, a primeira solução assumida é substituída no lado direito das equações e os novos valores calculados para as incógnitas formam a segunda solução estimada.

As interações continuam da mesma forma e, quando o método dá certo, as soluções obtidas durante as interações sucessivas convergem para a solução real. Em um sistema com _n_ equações, as equações ex´lícitas para as incógnitas [xi] são:

$$
    x_i = \frac{1}{a_{ii}}[b_i - (\sum^{j=n}_{j=1,j\neq i} a_{ij}x_j)] \hspace1cm i = 1,2,...,n
$$

#### Condição para a convergência:

Para um sistemas de _n_ equações [a][x] = [b], uma condição suficiente para a convergência ocorre se, em cada uma das linhas da matriz de coeficientes [a], o valor absoluto do elemento diagonal for maior que a soma dos valores absolutos dos elementos fora da diagonal.

$$
    |a_{ii}| > \sum^{j=n}_{j=1, j \neq i} |a_{ij}|
$$

Quando essa condição é satisfeita, a matriz [a] é classificada como _**diagonalmente dominante**_, e o processo iterativo converge para a solução. A solução, no entanto, pode convergir mesmo quando a condição de dominância não é satisfeita, ou seja, essa condição é suficiente, mas não necessária para a convergência.

Especificamos a seguir dois métodos iterativos, sendo eles o método de Jacobi e o método de Gauss-Seidel. A diferença entre esses dois métodos está na maneira pela qual os novos valores calculados para as incógnitas são utilizados. No método de Jacobi, os valores das incógnitas no lado direito da equação são atualizados todos de uma vez no final de cada interação. No método de Gauss-Seidel, o valor de cada incógnita é atualizado e usado no cálculo da nova estimativa das demais incógnitas dentro da mesma interação.

#### Método iterativo de Jacobi:

No método de Jacobi, um valor inicial é escolhido para cada uma das incógnitas. Se não houver nenhuma informação a respeito dos valores aproximados das incógnitas, pode-se assumir que o valor inicial de todas elas seja igual a zero. A segunda estimativa da solução é calculada com a substituição da primeira estimativa no lado direito da equação explicita:

$$
    x^{(2)}_{i} = \frac{1}{a_{ii}}[b_i - (\sum^{j=n}_{j=1, j \neq i} a_{ij}x^{(k)}_{j})] \hspace1cm i = 1,2,...,n
$$

#### Método iterativo de Gauss-Seidel:

No método de Gauss-Seidel, valores iniciais são assumidos para as incógnitas, exceto x1. Se não houver nenhuma informação a respeito dos valores aproximados das incógnitas, pode-se assumir que o valor inicial de todas elas sejam zero. Os primeiros valores assumidos para as incógnitas são substituídos na equação com i = 1 para calcular o valor de x1 e continua até i = n.

No método de Gauss-Seidel, os valores atuais das incógnitas são utilizados no cálculo do novo valor da próxima incógnita. Em outras palavras, à medida que um novo valor é calculado, ele é imediaramente utilizado na próxima aplicação da equação.

A aplicação do método de Gauss-Seidel leva a seguinte formula interativa:

$$
    x^{(k+1)}_{i} = \frac{1}{a_{ii}} [b_i - (\sum^{j=i-1}_{j=1}a_{ij}x^{k+1}_{j} + \sum^{j=n}_{j=i+1}a_{ij}x^{k}_{j})] \hspace1cm i = 2,3,...,n-1
$$

#### Algoritmos:

- Importações:

In [1]:
import numpy as np
import math

In [2]:
def isDominant(A, dim):
    
    coefs = []
    for i in range(0, dim):
        soma = 0
        for j in range(0, dim):
            if i != j:
                soma += math.fabs(A[i, j])
        if A[i,i] == 0:
            return False
        coefs.append(soma/math.fabs(A[i,i]))
        
    if max(coefs) < 1:
        return True
    return False

In [3]:
def gaussJacobi(A, b, x, dim, maxInt = 0, pres = 1e-3):
    
    # Verificando se a matriz garante a convergência:
    if not isDominant(A,dim):
        print("ALERTA: A convergência não está garantida. A matriz não é dominante!")
        res = input('Continuar? y/n\n >> ')
        if not res == 'y' or not res == 'Y':
            return
    
    k = 1
    while(k <= maxInt):
        
        print('Matriz A:\n{0}\nVetor b:\n{1}\nVetor x:\n{2}\n'.format(A, b, x))
        
        print('Interação {0}:\n'.format(k))
        
        x_novo = np.zeros(dim)
        
        for i in range(0,dim):
            soma = 0
            for j in range(0,dim):
                if j != i:
                    print('Soma parcial = soma + (A[{0},{1}] * x[{1}]) = {2} + {3}*{4}'.format(i, j, soma, A[i,j],x[j]))
                    soma += A[i,j]*x[j]
            print('Soma total = {}\n'.format(soma))
            
            x_novo[i] = (b[i] - soma)/A[i,i]
            print('x_novo[{0}] = (b[{0}] - soma)/A[{0},{0}] = ({1} - {2})/{3} = {4}\n'.format(i, b[i], soma, A[i,i], x_novo[i]))
        
        #if k != 1:
        #    e = (x_novo - x)/x
        #    print('Vetor erro estimado:{0}'.format(e))
        #    
        #    if math.fabs(max(e)) < pres:
        #        x = x_novo.copy()
        #        return x
        
        print('x ({0}) = x_novo ({1})'.format(x, x_novo))
        x = x_novo.copy()
        print('x = {0}\n'.format(x))
        
        k += 1
        print('\n')
    return x

 
 
 
 
 
 
 
 
 
 
 
 SEIDAL
 
 
 
 
 

In [ ]:
def gaussSeidel(A, b, x, dim, maxInt = 0, pres = 1e-3):
    
    # Verificando se a matriz garante a convergência:
    if not isDominant(A,dim):
        print("ALERTA: A convergência não está garantida. A matriz não é dominante!")
        res = input('Continuar? y/n\n >> ')
        if not res == 'y' or not res == 'Y':
            return
    
    k = 1
    while(k <= maxInt):
        
        print('Matriz A:\n{0}\nVetor b:\n{1}\nVetor x:\n{2}\n'.format(A, b, x))
        
        print('Interação {0}:\n'.format(k))
        
        x_novo = x.copy()
        
        for i in range(0,dim):
            soma = 0
            for j in range(0,dim):
                if j != i:
                    if i < j:
                        print('Soma parcial = soma + (A[{0},{1}] * x[{1}]) = {2} + {3}*{4}'.format(i, j, soma, A[i,j],x[j]))
                        soma += A[i,j]*x[j]
                    else:
                        print('Soma parcial = soma + (A[{0},{1}] * x_novo[{1}]) = {2} + {3}*{4}'.format(i, j, soma, A[i,j],x_novo[j]))
                        soma += A[i,j]*x_novo[j]
            print('Soma total = {}\n'.format(soma))
            
            x_novo[i] = (b[i] - soma)/A[i,i]
            print('x_novo[{0}] = (b[{0}] - soma)/A[{0},{0}] = ({1} - {2})/{3} = {4}\n'.format(i, b[i], soma, A[i,i], x_novo[i]))
        
       # if k != 1:
       #     e = (x_novo - x)/x
       #     print('Vetor erro estimado:{0}'.format(e))
            
       #     if math.fabs(max(e)) < pres:
       #         print(math.fabs(max(e)))
       #         x = x_novo.copy()
       #         return x
        
        print('x ({0}) = x_novo ({1})'.format(x, x_novo))
        x = x_novo.copy()
        print('x = {0}\n'.format(x))
        
        k += 1
        print('\n')
    return x

In [6]:
A = np.array(
        [
            [1.0, 0.2, 0.35],
            [0.05, -4.0, 0.35],
            [-0.05, -0.2, 7.0]
        ]
    )

b = np.array([4.0,7.0,28.0])

x = np.array([0.0,0.0,0.0])

dim = 3

gaussJacobi(A, b, x, dim, maxInt = 3, pres = 1e-9)

Matriz A:
[[ 1.    0.2   0.35]
 [ 0.05 -4.    0.35]
 [-0.05 -0.2   7.  ]]
Vetor b:
[ 4.  7. 28.]
Vetor x:
[0. 0. 0.]

Interação 1:

Soma parcial = soma + (A[0,1] * x[1]) = 0 + 0.2*0.0
Soma parcial = soma + (A[0,2] * x[2]) = 0.0 + 0.35*0.0
Soma total = 0.0

x_novo[0] = (b[0] - soma)/A[0,0] = (4.0 - 0.0)/1.0 = 4.0

Soma parcial = soma + (A[1,0] * x[0]) = 0 + 0.05*0.0
Soma parcial = soma + (A[1,2] * x[2]) = 0.0 + 0.35*0.0
Soma total = 0.0

x_novo[1] = (b[1] - soma)/A[1,1] = (7.0 - 0.0)/-4.0 = -1.75

Soma parcial = soma + (A[2,0] * x[0]) = 0 + -0.05*0.0
Soma parcial = soma + (A[2,1] * x[1]) = 0.0 + -0.2*0.0
Soma total = 0.0

x_novo[2] = (b[2] - soma)/A[2,2] = (28.0 - 0.0)/7.0 = 4.0

x ([0. 0. 0.]) = x_novo ([ 4.   -1.75  4.  ])
x = [ 4.   -1.75  4.  ]



Matriz A:
[[ 1.    0.2   0.35]
 [ 0.05 -4.    0.35]
 [-0.05 -0.2   7.  ]]
Vetor b:
[ 4.  7. 28.]
Vetor x:
[ 4.   -1.75  4.  ]

Interação 2:

Soma parcial = soma + (A[0,1] * x[1]) = 0 + 0.2*-1.75
Soma parcial = soma + (A[0,2] * x[2]) = -0.3

array([ 2.8775, -1.365 ,  3.9825])